spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    password: xxx
    database: 0
    lettuce:
      pool:
        max-active: 50
        min-idle: 10
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  datasource:
    # mysql5.5 及以上才使用 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: ywm735929
